#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-rapidfuzz_capi
Version  : 1.0.5
Release  : 1
URL      : https://files.pythonhosted.org/packages/60/ff/1c286397969c5926e4a8b0dbe7fcc138f0d731aac935ee68a3cb4e4293d5/rapidfuzz_capi-1.0.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/60/ff/1c286397969c5926e4a8b0dbe7fcc138f0d731aac935ee68a3cb4e4293d5/rapidfuzz_capi-1.0.5.tar.gz
Summary  : C-API of RapidFuzz, which can be used to extend RapidFuzz from separate packages
Group    : Development/Tools
License  : MIT
Requires: pypi-rapidfuzz_capi-python = %{version}-%{release}
Requires: pypi-rapidfuzz_capi-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
## RapidFuzz C-API
[![Continous Integration](https://github.com/maxbachmann/rapidfuzz_capi/workflows/Build/badge.svg)](https://github.com/maxbachmann/rapidfuzz_capi/actions)
[![GitHub License](https://img.shields.io/github/license/maxbachmann/rapidfuzz_capi)](https://github.com/maxbachmann/rapidfuzz_capi/blob/main/LICENSE)

%package python
Summary: python components for the pypi-rapidfuzz_capi package.
Group: Default
Requires: pypi-rapidfuzz_capi-python3 = %{version}-%{release}

%description python
python components for the pypi-rapidfuzz_capi package.


%package python3
Summary: python3 components for the pypi-rapidfuzz_capi package.
Group: Default
Requires: python3-core
Provides: pypi(rapidfuzz_capi)

%description python3
python3 components for the pypi-rapidfuzz_capi package.


%prep
%setup -q -n rapidfuzz_capi-1.0.5
cd %{_builddir}/rapidfuzz_capi-1.0.5
pushd ..
cp -a rapidfuzz_capi-1.0.5 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664334085
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
